### PR TITLE
balena-config-karma: update to v3.0.0

### PR DESCRIPTION
**Pull request by JSReds**
update balena-config-karma to v3.0.0

Change-type: patch
Signed-off-by: Andrea Rosci <andrear@balena.io>

### CODE REVIEW

**Comment by JSReds** [comment]
@thgreasi investigating why is still breaking

**Comment by thgreasi** [comment]
@JSReds try copying the karma.conf.js. I suspect the balel loaded might not play well with the new balena-config-karma.

**Comment by JSReds** [comment]
@thgreasi I'll give it another try right after support, karma-config does not seem to solve the entire problem

**Comment by thgreasi** [comment]
Let me know if you want me to also take a look.

**Comment by thgreasi** [comment]
@balena-ci retest

**Comment by thgreasi** [comment]
At least now tests pass on travis

**Comment by thgreasi** [comment]
And browser tests complete on balenaCI :tada: 
Looks like that if we drop `catch-uncommited` from the `npm test` balenaCI tests will also pass.

**Review by thgreasi — APPROVED** [review]

**Pull request merged**
